In [64]:
import pandas as pd

In [65]:
df = pd.read_parquet('grade_summary.parquet')

In [66]:
df.columns

Index(['idx', 'codigo', 'nombre', 'period', 'lect', 'esp', 'mat', 'econ',
       'ingl', 'qui', 'fis', 'filo', 'poli', 'ere', 'edufi', 'tecn', 'compo',
       'performance', 'fundamental', 'band'],
      dtype='object')

In [67]:
class StudentBase():
    id : int 
    name : str | None = None
    age : int
    social_data : int | None = None
    overall_grade : str
    fundamental_comp : str
    behavioral_comp : str
    disabilities : str | None

In [68]:
student_base = df[
    [
        'codigo', #id
        'nombre', #name
        #age,
        #social_data,
        'band', #overall
        'fundamental', #fundamental
        'compo'
    ]
].reset_index().drop(columns=['index'])

In [69]:
student_base.codigo.value_counts().reset_index()[student_base.codigo.value_counts().reset_index()['count'] > 2]

Empty DataFrame
Columns: [codigo, count]
Index: []

In [70]:
student_base['age'] = 16

In [71]:
student_base['social_data'] = None

In [72]:
student_base = student_base[['codigo', 'nombre', 'age', 'social_data', 'fundamental', 'band', 'compo']]

In [73]:
student_base.rename(
    columns={
        "codigo" : "id",
        "nombre" : "name",
        "fundamental" : "fundamental_comp",
        "band" : "overall_grade",
        "compo" : "behavioral_comp"
    },
    inplace=True
)

In [74]:
student_base["disabilities"] = None

In [75]:
student_base

,id,name,age,social_data,fundamental_comp,overall_grade,behavioral_comp,disabilities
0,2018,AGUILERA LOPEZ BREYNER SANTIAGO,16,None,7.0,HIGH,2.0,None
1,2019,AMASO GARCIA YADI MILARIS,16,None,8.0,HIGH,2.0,None
2,2022,BELTRAN VARON JHON ALEJANDRO,16,None,5.0,HIGH,2.0,None
3,907,BONILLA LOPEZ ANDRES FELIPE,16,None,4.0,MEDIUM,2.0,None
4,1226,BRICEÑO MARTINEZ SERGIO ANDRES,16,None,4.0,MEDIUM,1.0,None
...,...,...,...,...,...,...,...,...
559,1155,VERA RODRIGUEZ DAVID SANTIAGO,16,None,4.0,MEDIUM,3.0,None
560,87,YOTAGRI PADILLA DANIEL,16,None,4.0,MEDIUM,2.0,None
561,88,YOTAGRI PADILLA HONNER SANTIAGO,16,None,5.0,MEDIUM,2.0,None
562,89,YOTAGRI PADILLA JAMER ANDREY,16,None,6.0,HIGH,3.0,None
563,91,ZAPATA TOBO YORLADY VALENTINA,16,None,4.0,MEDIUM,3.0,None

In [77]:
student_base.to_json('student_info.json', orient='records')